[package]
name = "mesh2sculptr"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tobj = "3.0.1"
meshvox = "0.2.3"
csv = "1.0.0-beta.1"
clap = "2.33.3"